// Article Discovery Learning System
// -----------------------------------
// Central place for all the "learn from your daily cleanup" signals:
//   1. Per-site dismissal ratios (health pill in the filter bar)
//   2. Category+site learning (auto-block noisy categories on noisy sites)
//   3. Positive-signal brand boosting (mine your last N stereonet articles)
//   4. Hot-Story clustering (3+ external sites in 24h on same product/brand)
//   5. Weekly learning digest generation
//
// All functions here are pure DB read/write helpers. Route wiring lives in
// routes.ts (see the /api/discovery-learning/* handlers).

import Database from "better-sqlite3";
import type { Express } from "express";

// Types — kept loose because the sqlite handle isn't exported with strong types.
type DB = Database.Database;

// ─── Schema bootstrapping ────────────────────────────────────────────────────

export function ensureLearningSchema(sqlite: DB) {
  // Per-site ingest filters. When a row exists for a given site_key, the
  // insertArticle() choke-point enforces category and URL allowlists BEFORE
  // writing to articles. This is the sledgehammer: general-tech sites like
  // gearpatrol get audio-only filtering so we don't have to learn to hide
  // the 89% of their content that's watches, footwear, motoring, etc.
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS site_ingest_filters (
      site_key TEXT PRIMARY KEY,
      categories_include_json TEXT NOT NULL DEFAULT '[]',
      url_include_patterns_json TEXT NOT NULL DEFAULT '[]',
      note TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE TABLE IF NOT EXISTS site_ingest_filter_drops (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site TEXT NOT NULL,
      title TEXT,
      url TEXT,
      categories_json TEXT,
      dropped_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE INDEX IF NOT EXISTS idx_ingest_drops_site ON site_ingest_filter_drops(site, dropped_at DESC);
  `);

  // Learned category+site suppressions. Distinct from the free-text blocked
  // keywords list — this is structured (site, category) so we can render it
  // clearly in the admin panel and undo per-row.
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS discovery_learned_categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site TEXT NOT NULL,
      category TEXT NOT NULL,
      dismissed_count INTEGER NOT NULL DEFAULT 0,
      kept_count INTEGER NOT NULL DEFAULT 0,
      source TEXT NOT NULL DEFAULT 'learned',
      is_active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      last_seen_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_learned_cat_uniq ON discovery_learned_categories(site, category);
  `);

  // Positive-signal cache: brands StereoNET actively covers. Rebuilt periodically
  // from the last N stereonet articles' brand extractions.
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS discovery_positive_brands (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      brand TEXT NOT NULL UNIQUE,
      stereonet_article_count INTEGER NOT NULL DEFAULT 0,
      last_seen_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE INDEX IF NOT EXISTS idx_pos_brands_count ON discovery_positive_brands(stereonet_article_count DESC);
  `);

  // Hot-Story clusters. Each row is a cluster of 3+ external articles about
  // the same product within 24h that StereoNET has not yet published on.
  // Regenerated by the periodic clusterHotStories() call.
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS discovery_hot_clusters (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      cluster_key TEXT NOT NULL UNIQUE,
      brand TEXT,
      product TEXT,
      article_ids_json TEXT NOT NULL,
      site_count INTEGER NOT NULL,
      first_seen_at TEXT NOT NULL,
      last_seen_at TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'open',
      dismissed_at TEXT,
      dismissed_by TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE INDEX IF NOT EXISTS idx_hot_status ON discovery_hot_clusters(status, last_seen_at DESC);
  `);
}

// ─── 1. Per-site dismissal stats ─────────────────────────────────────────────

export interface SiteHealth {
  site: string;
  articles_30d: number;
  dismissed_30d: number;
  kept_30d: number;
  dismissal_ratio: number;
  health: "green" | "amber" | "red" | "unknown";
}

export function computeSiteHealth(sqlite: DB): SiteHealth[] {
  const rows = sqlite.prepare(`
    SELECT
      a.site,
      COUNT(*) as articles_30d,
      SUM(CASE WHEN d.article_id IS NOT NULL THEN 1 ELSE 0 END) as dismissed_30d,
      SUM(CASE WHEN c.article_id IS NOT NULL AND c.status IN ('claimed','written') THEN 1 ELSE 0 END) as kept_30d
    FROM articles a
    LEFT JOIN article_dismissals d ON d.article_id = a.id
    LEFT JOIN article_claims c ON c.article_id = a.id
    WHERE a.fetched_at >= datetime('now', '-30 days')
      AND a.site NOT IN ('stereonet', 'headfi')
    GROUP BY a.site
    ORDER BY articles_30d DESC
  `).all() as any[];

  return rows.map(r => {
    const articles = Number(r.articles_30d || 0);
    const dismissed = Number(r.dismissed_30d || 0);
    const kept = Number(r.kept_30d || 0);
    const ratio = articles > 0 ? dismissed / articles : 0;
    let health: SiteHealth["health"] = "unknown";
    if (articles < 20) {
      health = "unknown"; // not enough signal
    } else if (ratio >= 0.85) {
      health = "red"; // 85%+ dismissed — this feed is noisy
    } else if (ratio >= 0.6) {
      health = "amber"; // 60-85% dismissed — worth reviewing
    } else {
      health = "green"; // <60% dismissed — feed is relevant
    }
    return {
      site: r.site,
      articles_30d: articles,
      dismissed_30d: dismissed,
      kept_30d: kept,
      dismissal_ratio: Math.round(ratio * 100) / 100,
      health,
    };
  });
}

// ─── 2. Category learning ────────────────────────────────────────────────────

// Aggressive-mode threshold: for sites where the overall 30d keep ratio is
// very low (<5% of ingested articles led to a keep/claim), we drop the auto-
// activate bar to 3+ dismissals with 0 keeps. This is what caught the
// gearpatrol "style", "today in gear", "tech", "home" and similar categories
// where only a handful of dismissals happened but the site's overall signal
// is that we don't cover their content.
export function getAggressiveModeSites(sqlite: DB): Set<string> {
  try {
    const rows = sqlite.prepare(`
      SELECT a.site,
             COUNT(*) as articles_30d,
             SUM(CASE WHEN c.article_id IS NOT NULL AND c.status IN ('claimed','written') THEN 1 ELSE 0 END) as kept_30d
      FROM articles a
      LEFT JOIN article_claims c ON c.article_id = a.id
      WHERE a.fetched_at >= datetime('now', '-30 days')
        AND a.site NOT IN ('stereonet', 'headfi', 'editor-brief', 'email_pressroom', 'webhook')
      GROUP BY a.site
      HAVING articles_30d >= 30
    `).all() as any[];
    const aggressive = new Set<string>();
    for (const r of rows) {
      const articles = Number(r.articles_30d || 0);
      const kept = Number(r.kept_30d || 0);
      const keepRatio = articles > 0 ? kept / articles : 1;
      if (keepRatio < 0.05) aggressive.add(r.site); // less than 5% kept
    }
    return aggressive;
  } catch {
    return new Set<string>();
  }
}

// Look at every dismissed article in the last 60 days and rebuild category+site
// counters. Auto-activate (site, category) pairs that have 5+ dismissals and
// 0 keeps (claims/writes/published stereonet match).
// For sites in aggressive mode (see getAggressiveModeSites), the threshold
// drops to 3+ dismissals + 0 keeps.
export function learnCategoriesFromDismissals(sqlite: DB): { learned: number; reviewed: number; aggressive_sites: string[] } {
  const rows = sqlite.prepare(`
    SELECT
      a.site,
      a.categories,
      SUM(CASE WHEN d.article_id IS NOT NULL THEN 1 ELSE 0 END) as dismissed_cnt,
      SUM(CASE WHEN c.article_id IS NOT NULL AND c.status IN ('claimed','written') THEN 1 ELSE 0 END) as kept_cnt
    FROM articles a
    LEFT JOIN article_dismissals d ON d.article_id = a.id
    LEFT JOIN article_claims c ON c.article_id = a.id
    WHERE a.fetched_at >= datetime('now', '-60 days')
      AND a.categories IS NOT NULL
      AND a.categories != ''
      AND a.categories != '[]'
      AND a.site NOT IN ('stereonet', 'headfi')
    GROUP BY a.id
  `).all() as any[];

  const combo = new Map<string, { site: string; category: string; dismissed: number; kept: number }>();
  for (const r of rows) {
    let cats: string[] = [];
    try { cats = JSON.parse(r.categories || "[]"); } catch { cats = []; }
    if (!Array.isArray(cats)) continue;
    for (const catRaw of cats) {
      const cat = String(catRaw || "").trim().toLowerCase();
      if (!cat || cat.length < 2 || cat.length > 60) continue;
      // Skip generic catch-all categories
      if (["news", "featured", "audio", "video", "gear", "products", "reviews"].includes(cat)) continue;
      const key = `${r.site}::${cat}`;
      const existing = combo.get(key) || { site: r.site, category: cat, dismissed: 0, kept: 0 };
      existing.dismissed += Number(r.dismissed_cnt || 0);
      existing.kept += Number(r.kept_cnt || 0);
      combo.set(key, existing);
    }
  }

  const upsert = sqlite.prepare(`
    INSERT INTO discovery_learned_categories (site, category, dismissed_count, kept_count, source, is_active, last_seen_at)
    VALUES (?, ?, ?, ?, 'learned', ?, datetime('now'))
    ON CONFLICT(site, category) DO UPDATE SET
      dismissed_count = excluded.dismissed_count,
      kept_count = excluded.kept_count,
      is_active = excluded.is_active,
      last_seen_at = excluded.last_seen_at
  `);

  const aggressiveSites = getAggressiveModeSites(sqlite);

  let learned = 0;
  for (const c of combo.values()) {
    // Auto-active rule: 5+ dismissals, 0 keeps, ratio >= 90%
    // Aggressive mode (low-keep-ratio site): 3+ dismissals, 0 keeps, ratio >= 90%
    const total = c.dismissed + c.kept;
    const ratio = total > 0 ? c.dismissed / total : 0;
    const minDismiss = aggressiveSites.has(c.site) ? 3 : 5;
    const shouldActivate = c.dismissed >= minDismiss && c.kept === 0 && ratio >= 0.9;
    // Preserve manual overrides — only auto-write learned rows.
    const existing = sqlite.prepare(`SELECT source, is_active FROM discovery_learned_categories WHERE site = ? AND category = ?`).get(c.site, c.category) as any;
    const isActive = existing?.source === "manual" ? existing.is_active : (shouldActivate ? 1 : 0);
    upsert.run(c.site, c.category, c.dismissed, c.kept, isActive);
    if (isActive) learned++;
  }
  return { learned, reviewed: combo.size, aggressive_sites: Array.from(aggressiveSites) };
}

// Returns the active (site, category) suppression set for the discovery filter.
export function getActiveCategorySuppressions(sqlite: DB): Set<string> {
  const rows = sqlite.prepare(`SELECT site, category FROM discovery_learned_categories WHERE is_active = 1`).all() as any[];
  return new Set(rows.map(r => `${r.site}::${String(r.category).toLowerCase()}`));
}

// ─── 3. Positive brand signal ────────────────────────────────────────────────

// Rebuild the positive-brands cache by mining the last N StereoNET articles'
// brands + titles for repeated brand mentions.
export function rebuildPositiveBrands(sqlite: DB, lookbackDays = 90, minCount = 2): number {
  // Wipe and recompute
  sqlite.prepare(`DELETE FROM discovery_positive_brands`).run();

  const rows = sqlite.prepare(`
    SELECT title, brands
    FROM articles
    WHERE site = 'stereonet'
      AND published_at >= datetime('now', '-' || ? || ' days')
  `).all(lookbackDays) as any[];

  const brandCount = new Map<string, number>();
  for (const r of rows) {
    // Prefer structured brands array if present
    let brands: string[] = [];
    try { brands = JSON.parse(r.brands || "[]"); } catch { brands = []; }
    if (!Array.isArray(brands) || brands.length === 0) {
      // fallback: try to extract known brand-like tokens from the title
      brands = extractBrandsFromTitle(r.title || "");
    }
    const seen = new Set<string>();
    for (const bRaw of brands) {
      const b = String(bRaw || "").trim().toLowerCase();
      if (!b || b.length < 2 || b.length > 40) continue;
      if (isBrandNoise(b)) continue;
      if (seen.has(b)) continue;
      seen.add(b);
      brandCount.set(b, (brandCount.get(b) || 0) + 1);
    }
  }

  const upsert = sqlite.prepare(`
    INSERT OR REPLACE INTO discovery_positive_brands (brand, stereonet_article_count, last_seen_at)
    VALUES (?, ?, datetime('now'))
  `);
  let inserted = 0;
  for (const [brand, count] of brandCount.entries()) {
    if (count < minCount) continue;
    upsert.run(brand, count);
    inserted++;
  }
  return inserted;
}

// Returns the set of positive brands (lowercased) for quick membership tests
// during Discovery ranking.
export function getPositiveBrandsSet(sqlite: DB): Set<string> {
  const rows = sqlite.prepare(`SELECT brand FROM discovery_positive_brands`).all() as any[];
  return new Set(rows.map(r => String(r.brand).toLowerCase()));
}

// ─── 4. Hot-Story clustering ─────────────────────────────────────────────────

// Look at the last 24h of external articles and cluster them by shared brand/
// product tokens. A cluster becomes a "Hot Story" when 3+ distinct sites are in it
// and StereoNET has NOT published on that brand/product in the last 24h.
export function clusterHotStories(sqlite: DB): { clusters_open: number; clusters_new: number } {
  // 1. Fetch external articles from the last 24h that are still visible in Discovery
  const externals = sqlite.prepare(`
    SELECT id, site, title, brands, published_at, url
    FROM articles
    WHERE fetched_at >= datetime('now', '-24 hours')
      AND site NOT IN ('stereonet', 'headfi')
    ORDER BY fetched_at DESC
  `).all() as any[];

  // 2. Fetch stereonet articles from the same window so we can suppress covered clusters
  const stereonetRows = sqlite.prepare(`
    SELECT title, brands
    FROM articles
    WHERE site = 'stereonet'
      AND published_at >= datetime('now', '-24 hours')
  `).all() as any[];

  const stereonetTokens = new Set<string>();
  for (const s of stereonetRows) {
    let bs: string[] = [];
    try { bs = JSON.parse(s.brands || "[]"); } catch {}
    if (!Array.isArray(bs)) bs = [];
    if (bs.length === 0) bs = extractBrandsFromTitle(s.title || "");
    for (const b of bs) {
      const key = normaliseBrandProduct(b);
      if (key) stereonetTokens.add(key);
    }
    // Also index title bigrams to catch product names not in structured brands
    for (const bg of titleBigrams(s.title || "")) stereonetTokens.add(bg);
  }

  // 3. Bucket externals by normalised brand/product token
  const buckets = new Map<string, { ids: number[]; sites: Set<string>; brand: string; product: string; first: string; last: string }>();
  for (const a of externals) {
    let bs: string[] = [];
    try { bs = JSON.parse(a.brands || "[]"); } catch {}
    if (!Array.isArray(bs)) bs = [];
    if (bs.length === 0) bs = extractBrandsFromTitle(a.title || "");
    // Also derive title bigrams as candidate product tokens
    const candidates = new Set<string>();
    for (const b of bs) {
      const norm = normaliseBrandProduct(b);
      if (norm) candidates.add(norm);
    }
    for (const bg of titleBigrams(a.title || "")) {
      if (bg.length >= 8) candidates.add(bg); // longer bigrams only, avoid noise
    }
    // Pick the most-specific candidate for bucketing (longest)
    const best = Array.from(candidates).sort((x, y) => y.length - x.length)[0];
    if (!best) continue;
    // Suppress if stereonet already covered
    if (stereonetTokens.has(best)) continue;
    const b = buckets.get(best) || { ids: [], sites: new Set<string>(), brand: best, product: best, first: a.published_at, last: a.published_at };
    b.ids.push(a.id);
    b.sites.add(a.site);
    if (a.published_at < b.first) b.first = a.published_at;
    if (a.published_at > b.last) b.last = a.published_at;
    buckets.set(best, b);
  }

  // 4. Persist buckets with 3+ distinct sites as hot clusters
  let openCount = 0, newCount = 0;
  const upsert = sqlite.prepare(`
    INSERT INTO discovery_hot_clusters (cluster_key, brand, product, article_ids_json, site_count, first_seen_at, last_seen_at, status)
    VALUES (?, ?, ?, ?, ?, ?, ?, 'open')
    ON CONFLICT(cluster_key) DO UPDATE SET
      article_ids_json = excluded.article_ids_json,
      site_count = excluded.site_count,
      last_seen_at = excluded.last_seen_at,
      status = CASE WHEN discovery_hot_clusters.status = 'dismissed' THEN 'dismissed' ELSE 'open' END
  `);
  for (const [key, b] of buckets.entries()) {
    if (b.sites.size < 3) continue;
    const info = upsert.run(key, b.brand, b.product, JSON.stringify(b.ids), b.sites.size, b.first, b.last);
    if (info.changes > 0) {
      const row = sqlite.prepare(`SELECT status, created_at FROM discovery_hot_clusters WHERE cluster_key = ?`).get(key) as any;
      if (row?.status === "open") openCount++;
      if (row?.created_at && row.created_at >= new Date(Date.now() - 30 * 60_000).toISOString().replace("T", " ").slice(0, 19)) {
        newCount++;
      }
    }
  }

  // 5. Age-out: mark clusters as 'stale' if last_seen_at older than 72h
  sqlite.prepare(`UPDATE discovery_hot_clusters SET status = 'stale' WHERE status = 'open' AND last_seen_at < datetime('now', '-72 hours')`).run();

  const open = sqlite.prepare(`SELECT COUNT(*) as n FROM discovery_hot_clusters WHERE status = 'open'`).get() as any;
  return { clusters_open: Number(open?.n || 0), clusters_new: newCount };
}

export function getOpenHotClusters(sqlite: DB) {
  return sqlite.prepare(`
    SELECT hc.id, hc.cluster_key, hc.brand, hc.product, hc.article_ids_json, hc.site_count,
           hc.first_seen_at, hc.last_seen_at, hc.status
    FROM discovery_hot_clusters hc
    WHERE hc.status = 'open'
    ORDER BY hc.site_count DESC, hc.last_seen_at DESC
  `).all();
}

// ─── 5. Weekly digest ────────────────────────────────────────────────────────

// Build a summary of the last 7 days of Discovery activity: what got dismissed,
// which sites are noisiest, and suggest new keywords / category blocks.
export function buildWeeklyDigest(sqlite: DB) {
  const dismissedRows = sqlite.prepare(`
    SELECT a.site, a.title, a.categories, d.dismissed_at
    FROM article_dismissals d
    JOIN articles a ON a.id = d.article_id
    WHERE d.dismissed_at >= datetime('now', '-7 days')
    ORDER BY d.dismissed_at DESC
  `).all() as any[];

  const bySite = new Map<string, number>();
  const byCategory = new Map<string, { site: string; cat: string; n: number }>();
  const titleTokens = new Map<string, number>();

  for (const r of dismissedRows) {
    bySite.set(r.site, (bySite.get(r.site) || 0) + 1);
    // Category tally
    let cats: string[] = [];
    try { cats = JSON.parse(r.categories || "[]"); } catch {}
    if (Array.isArray(cats)) {
      for (const c of cats) {
        const key = `${r.site}::${String(c).toLowerCase()}`;
        const cur = byCategory.get(key) || { site: r.site, cat: String(c).toLowerCase(), n: 0 };
        cur.n++;
        byCategory.set(key, cur);
      }
    }
    // Title token tally (bigrams, min length 8)
    for (const bg of titleBigrams(r.title || "")) {
      if (bg.length < 8) continue;
      if (isBrandNoise(bg)) continue;
      titleTokens.set(bg, (titleTokens.get(bg) || 0) + 1);
    }
  }

  // Kept/pinned articles (positive signal)
  const keptRows = sqlite.prepare(`
    SELECT COUNT(DISTINCT c.article_id) as n
    FROM article_claims c
    WHERE c.claimed_at >= datetime('now', '-7 days')
  `).get() as any;

  return {
    week_ending: new Date().toISOString().slice(0, 10),
    total_dismissed: dismissedRows.length,
    total_kept: Number(keptRows?.n || 0),
    dismissals_by_site: Array.from(bySite.entries())
      .map(([site, n]) => ({ site, n }))
      .sort((a, b) => b.n - a.n)
      .slice(0, 10),
    dismissals_by_category: Array.from(byCategory.values())
      .filter(c => c.n >= 3)
      .sort((a, b) => b.n - a.n)
      .slice(0, 15),
    suggested_block_phrases: Array.from(titleTokens.entries())
      .filter(([_, n]) => n >= 3)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20)
      .map(([phrase, n]) => ({ phrase, n })),
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const BRAND_NOISE = new Set([
  "the", "and", "for", "with", "from", "this", "that", "new", "best", "just", "will",
  "one", "two", "three", "four", "five", "big", "small", "high", "low", "hi", "fi",
  "audio", "sound", "music", "speaker", "speakers", "headphone", "headphones",
  "review", "reviews", "news", "test", "tests", "guide", "guides", "buying",
  "price", "prices", "cost", "value", "deal", "deals", "sale", "sales",
  "featured", "products", "product", "brand", "brands", "collection",
  "legendary", "beloved", "revives", "reimagined", "iconic", "flagship",
  "series", "range", "lineup", "line-up",
  "black", "white", "silver", "gold", "red", "blue",
  "wireless", "portable", "smart", "connected", "premium",
  "generation", "second", "third", "fourth",
  "our", "your", "their", "his", "her", "its",
  "audio-technica", // hyphen edge case
]);

function isBrandNoise(word: string): boolean {
  if (!word) return true;
  if (word.length < 3) return true;
  if (/^\d+$/.test(word)) return true;
  return BRAND_NOISE.has(word);
}

function normaliseBrandProduct(raw: string): string | null {
  if (!raw) return null;
  const s = String(raw).trim().toLowerCase().replace(/\s+/g, " ");
  if (!s || s.length < 3 || s.length > 60) return null;
  // reject if it's just noise
  const parts = s.split(" ");
  if (parts.every(p => isBrandNoise(p))) return null;
  return s;
}

function titleBigrams(title: string): string[] {
  const tokens = (title || "")
    .toLowerCase()
    .replace(/[^a-z0-9\-\s]/g, " ")
    .split(/\s+/)
    .filter(t => t.length >= 2 && !isBrandNoise(t));
  const out: string[] = [];
  for (let i = 0; i < tokens.length - 1; i++) {
    const bg = `${tokens[i]} ${tokens[i + 1]}`;
    if (bg.length >= 6) out.push(bg);
  }
  return out;
}

// Very light brand extraction from title — used only when the structured
// `brands` column is empty. Picks capitalised tokens that don't look like
// generic English words.
function extractBrandsFromTitle(title: string): string[] {
  const words = (title || "").split(/\s+/);
  const out: string[] = [];
  for (const w of words) {
    const cleaned = w.replace(/[^A-Za-z0-9\-]/g, "");
    if (!cleaned || cleaned.length < 3) continue;
    if (!/^[A-Z]/.test(cleaned)) continue;
    if (isBrandNoise(cleaned.toLowerCase())) continue;
    out.push(cleaned);
  }
  return out;
}

// ─── Route registration ──────────────────────────────────────────────────────

export function registerDiscoveryLearningRoutes(app: Express, sqlite: DB) {
  ensureLearningSchema(sqlite);

  // GET /api/discovery-learning/site-health — health pill data for filter bar
  app.get("/api/discovery-learning/site-health", (_req, res) => {
    try {
      const data = computeSiteHealth(sqlite);
      res.json({ ok: true, sites: data });
    } catch (e: any) {
      res.status(500).json({ ok: false, message: e?.message || "site-health failed" });
    }
  });

  // GET /api/discovery-learning/categories — list learned categories
  app.get("/api/discovery-learning/categories", (_req, res) => {
    const rows = sqlite.prepare(`
      SELECT id, site, category, dismissed_count, kept_count, source, is_active, last_seen_at
      FROM discovery_learned_categories
      ORDER BY is_active DESC, dismissed_count DESC
    `).all();
    res.json({ ok: true, categories: rows });
  });

  // POST /api/discovery-learning/categories/toggle — toggle a category on/off
  app.post("/api/discovery-learning/categories/toggle", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const id = Number(req.body?.id);
    const active = req.body?.is_active ? 1 : 0;
    if (!Number.isInteger(id)) return res.status(400).json({ message: "id required" });
    sqlite.prepare(`UPDATE discovery_learned_categories SET is_active = ?, source = 'manual' WHERE id = ?`).run(active, id);
    res.json({ ok: true });
  });

  // POST /api/discovery-learning/categories/recompute — force a learning pass
  app.post("/api/discovery-learning/categories/recompute", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const out = learnCategoriesFromDismissals(sqlite);
    res.json({ ok: true, ...out });
  });

  // GET /api/discovery-learning/positive-brands
  app.get("/api/discovery-learning/positive-brands", (_req, res) => {
    const rows = sqlite.prepare(`SELECT brand, stereonet_article_count, last_seen_at FROM discovery_positive_brands ORDER BY stereonet_article_count DESC LIMIT 300`).all();
    res.json({ ok: true, brands: rows });
  });

  // POST /api/discovery-learning/positive-brands/rebuild
  app.post("/api/discovery-learning/positive-brands/rebuild", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const lookback = Math.max(30, Math.min(365, Number(req.body?.lookback_days) || 90));
    const min = Math.max(1, Math.min(10, Number(req.body?.min_count) || 2));
    const inserted = rebuildPositiveBrands(sqlite, lookback, min);
    res.json({ ok: true, brands_indexed: inserted, lookback_days: lookback, min_count: min });
  });

  // GET /api/discovery-learning/hot-stories — open hot-story clusters
  app.get("/api/discovery-learning/hot-stories", (_req, res) => {
    const clusters = getOpenHotClusters(sqlite) as any[];
    // Hydrate: return the underlying articles too
    const out = clusters.map(c => {
      let ids: number[] = [];
      try { ids = JSON.parse(c.article_ids_json || "[]"); } catch {}
      if (!Array.isArray(ids) || !ids.length) return { ...c, articles: [] };
      const placeholders = ids.map(() => "?").join(",");
      const articles = sqlite.prepare(`
        SELECT id, site, title, url, published_at, description
        FROM articles WHERE id IN (${placeholders})
        ORDER BY published_at ASC
      `).all(...ids);
      return { ...c, articles };
    });
    res.json({ ok: true, clusters: out });
  });

  // POST /api/discovery-learning/hot-stories/recompute
  app.post("/api/discovery-learning/hot-stories/recompute", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const out = clusterHotStories(sqlite);
    res.json({ ok: true, ...out });
  });

  // POST /api/discovery-learning/hot-stories/:id/dismiss
  app.post("/api/discovery-learning/hot-stories/:id/dismiss", (req: any, res) => {
    if (!req.session?.username) return res.status(401).json({ message: "Unauthorized" });
    const id = Number(req.params.id);
    if (!Number.isInteger(id)) return res.status(400).json({ message: "invalid id" });
    sqlite.prepare(`UPDATE discovery_hot_clusters SET status = 'dismissed', dismissed_at = datetime('now'), dismissed_by = ? WHERE id = ?`).run(req.session.username, id);
    res.json({ ok: true });
  });

  // ─── Ingest filters (Fix 2) ───────────────────────────────────────

  // GET /api/discovery-learning/ingest-filters — list current per-site filters
  app.get("/api/discovery-learning/ingest-filters", (_req, res) => {
    const rows = sqlite.prepare(`SELECT site_key, categories_include_json, url_include_patterns_json, note, created_at, updated_at FROM site_ingest_filters ORDER BY site_key`).all();
    res.json({ ok: true, filters: rows });
  });

  // POST /api/discovery-learning/ingest-filters — upsert a filter
  app.post("/api/discovery-learning/ingest-filters", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const site = String(req.body?.site_key || "").trim().toLowerCase();
    if (!site) return res.status(400).json({ message: "site_key required" });
    const cats = Array.isArray(req.body?.categories_include) ? req.body.categories_include.map((c: any) => String(c).toLowerCase()) : [];
    const urls = Array.isArray(req.body?.url_include_patterns) ? req.body.url_include_patterns.map((p: any) => String(p).toLowerCase()) : [];
    const note = String(req.body?.note || "").trim() || null;
    sqlite.prepare(`
      INSERT INTO site_ingest_filters (site_key, categories_include_json, url_include_patterns_json, note, updated_at)
      VALUES (?, ?, ?, ?, datetime('now'))
      ON CONFLICT(site_key) DO UPDATE SET
        categories_include_json = excluded.categories_include_json,
        url_include_patterns_json = excluded.url_include_patterns_json,
        note = excluded.note,
        updated_at = datetime('now')
    `).run(site, JSON.stringify(cats), JSON.stringify(urls), note);
    res.json({ ok: true, site_key: site, categories_include: cats, url_include_patterns: urls });
  });

  // DELETE /api/discovery-learning/ingest-filters/:site_key
  app.delete("/api/discovery-learning/ingest-filters/:site_key", (req: any, res) => {
    if (req.session?.role !== "admin") return res.status(403).json({ message: "Admin only" });
    const site = String(req.params.site_key || "").trim().toLowerCase();
    sqlite.prepare(`DELETE FROM site_ingest_filters WHERE site_key = ?`).run(site);
    res.json({ ok: true });
  });

  // GET /api/discovery-learning/ingest-filter-drops — recent ingest drops
  app.get("/api/discovery-learning/ingest-filter-drops", (req, res) => {
    const site = String((req.query as any)?.site || "").trim().toLowerCase();
    const limit = Math.min(500, Math.max(10, Number((req.query as any)?.limit) || 100));
    let rows: any[];
    if (site) {
      rows = sqlite.prepare(`SELECT site, title, url, categories_json, dropped_at FROM site_ingest_filter_drops WHERE site = ? ORDER BY dropped_at DESC LIMIT ?`).all(site, limit) as any[];
    } else {
      rows = sqlite.prepare(`SELECT site, title, url, categories_json, dropped_at FROM site_ingest_filter_drops ORDER BY dropped_at DESC LIMIT ?`).all(limit) as any[];
    }
    // Aggregate: drops per site in last 24h
    const perSite = sqlite.prepare(`
      SELECT site, COUNT(*) as drops_24h
      FROM site_ingest_filter_drops
      WHERE dropped_at >= datetime('now', '-24 hours')
      GROUP BY site
      ORDER BY drops_24h DESC
    `).all();
    res.json({ ok: true, drops: rows, aggregates_24h: perSite });
  });

  // GET /api/discovery-learning/weekly-digest
  app.get("/api/discovery-learning/weekly-digest", (_req, res) => {
    try {
      const digest = buildWeeklyDigest(sqlite);
      res.json({ ok: true, digest });
    } catch (e: any) {
      res.status(500).json({ ok: false, message: e?.message || "digest failed" });
    }
  });
}
